<?php

/**
 * ProcessWire Modules Manager
 * created 2012 by Soma
 *
 * ProcessWire 2.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class ModulesManager extends Process implements ConfigurableModule {

	protected static $defaults = array(
			'apikey' => 'pw223',
			'remoteurl' => 'http://modules.processwire.com/export-json/',
			'limit' => 350,
			'max_redirects' => 3
		);

	// uninstallable
	protected $exclude_categories = array(
		'language-pack' => 'Language Packs',
		'site-profile' => 'Site Profiles'
		);

	protected $modulesArray = array();
	protected $modulesRemoteArray = array();
	protected $cacheFile = 'ModuleManager.cache';
	protected $downloadFileName = 'ModuleManagerDownload.zip';

	/**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Modules Manager',
			'version' => 111,
			'summary' => 'Browse Modules posted from modules.processwire.com. Download, update or install them. Consider this a proof of concept and use at your own risk.',
			'href' => '',
			'singular' => true,
			'autoload' => false,
			'permission' => 'modules-manager'
			);
	}

	/**
	 * get the config either default or overwritten by user config
	 * @param  string $key name of the option
	 * @return mixed      return requested option value
	 */
	public function getConfig($key) {
		return ($this->get($key)) ? $this->get($key) : self::$defaults[$key];
	}

	/**
	 * this method is called when ProcessWire is read and loaded the module
	 * used here to get scripts and css files loaded automatically
	 */
	public function init() {
		parent::init();

		$this->labelRequires = $this->_x("Requires", 'list'); // Label that precedes list of required prerequisite modules
		$this->labelInstalls = $this->_x("Also installs", 'list'); // Label that precedes list of required prerequisite modules
	}

	public function initModules() {
		// WORKAROUND FIX: cycle all modules to load them without installing them
		// so we can getModuleInfo(classname) to work for extending modules of modules that aren't yet installed/loaded
		// so dependencies for "requires" can be checked for modules that are downloaded
		foreach($this->modules as $module) {
			wire('modules')->getModuleInfo($module->className()); // fixes problems
		}
		// get current uninstalled modules with flag 0
		foreach($this->modules->getInstallable() as $module) {
			wire('modules')->getModuleInfo(basename($module, '.module')); // fixes problems
		}
	}


	/**
	 * used internally for the module to convert version numbers of the modules
	 * @param  int $version version number | major minor revision
	 * @return string          returns string formatted version number
	 */
	protected function formatVersion($version) {
		return preg_replace('/(\d)(?=\d)/', '$1.', str_pad( (string)$version, 3, '0', STR_PAD_LEFT));
	}

	/**
	 * Display the default admin screen with module list
	 *
	 * @return string output html string
	 */
	public function execute() {
		// check if we have the rights to download files from other domains
		// using copy or file_get_contents
		if(!ini_get('allow_url_fopen')) {
			$this->error($this->_('The php config `allow_url_fopen` is disabled on the server, modules cannot be downloaded through Modules Manages. Enable it or ask your hosting support then try again.'));
		}

		// check if directories are writeable
		if(!is_writable($this->config->paths->assets)) {
			$this->error($this->_('Make sure your /site/assets directory is writeable by PHP.'));
		}
		if(!is_writable($this->config->paths->siteModules)) {
			$this->error($this->_('Make sure your /site/modules directory is writeable by PHP.'));
		}

		// construct the cache file path for json feed
		$cache_file = $this->config->paths->cache . $this->cacheFile;

		// reset cache to scan for new modules downloaded, manually
		// put into site modules folder and download current JSON feed
		if($this->input->get->reset) {
			// reset PW modules cache
			$this->modules->resetCache();
			// json feed download and cache
			$this->createCacheFile($cache_file);
			// reload page without params
			$this->session->redirect('./');
		}

		// get json module feed cache file,
		// if not yet cached download and cache it
		if(file_exists($cache_file)){
			$this->modulesRemoteArray = $this->readCacheFile($cache_file);
		} else {
			$this->modulesRemoteArray = $this->createCacheFile($cache_file);
		}

		// get current installed modules in PW and store it in array
		// for later use to generate
		foreach($this->modules as $module) {
			$this->modulesArray[$module->className()] = 1;
			wire('modules')->getModuleInfo($module->className()); // fixes problems
		}
		// get current uninstalled modules with flag 0
		foreach($this->modules->getInstallable() as $module) {
			$this->modulesArray[basename($module, '.module')] = 0;
			wire('modules')->getModuleInfo(basename($module, '.module')); // fixes problems
		}

		$out = '';

		// start output of module list
		$this->module_table = wire('modules')->get('MarkupAdminDataTable');
		$this->module_table->setEncodeEntities(false);
		$header = array(
			$this->_('Name/Version'),
			$this->_('Module Title/Summary'),
			$this->_('Categories'),
			$this->_('Author(s)'),
			$this->_('Added'),
			$this->_('Modified'),
			$this->_('Likes'),
			$this->_('Status'),
			$this->_('Action')
		);

		$this->module_table->headerRow($header);

		$count = 0;
		$this->all_categories = array();

		// loop the module list we got from the json feed and we do
		// various checks here to see if it's up to date or installed
		foreach($this->modulesRemoteArray->items as $key => $module) {

			$categories = array();

			foreach($module->categories as $cat) $categories[$cat->name] = $cat->title;
			//$all_categories = array_merge($all_categories, $categories);
			$this->all_categories = array_merge($this->all_categories, $categories);

			// exclude modules
			$uninstallable = false;
			$filterout = false;

			// filter out unwanted categories
			foreach($this->exclude_categories as $k => $exc) {
				if(array_key_exists($k,$categories)){
					$uninstallable = true;
					break;
				}
			}

			// filter for selected category
			if( isset(wire('input')->get->cat) ) {
				$selected_cat = wire('input')->get->cat;
				if($selected_cat){
					if(!array_key_exists(wire('input')->get->cat, $categories)) {
						$filterout = true;
					}
				}
			}

			// if filtered out no need to go any further in the loop
			if($filterout) continue;
			// lets add a link to the modules.processwire.com instead

			$count++;

			$authors = array();
			foreach($module->authors as $auth) $authors[] = $auth->title;

			$status = '<span>-</span>';
			$version = '-';
			$actions = '-';
			$dependencies = '';

			$remote_version = $this->formatVersion($module->module_version);

			if(array_key_exists($module->class_name, $this->modulesArray)) {
				// get module infos, we can't use modules->get(module_name) here
				// as it would install the module, which we don't want at all

				$info = wire('modules')->getModuleInfo($module->class_name);
				$local_version = $this->formatVersion($info['version']);

				if($this->modulesArray[$module->class_name] == 0) {

					if(count($info['requires'])) {
						$requires = $this->modules->getRequiresForInstall($module->class_name);
						if(count($requires)) $dependencies .= "<br /><span class='notes'>$this->labelRequires - " . implode(', ', $requires) . "</span>";
					} else $requires = array();

					if(count($info['installs'])) {
						$dependencies .= "<br /><span class='detail'>$this->labelInstalls - " . implode(', ', $info['installs']) . "</span>";
					}

					$status = 'found: ' . $local_version;

					if(count($requires)) {
						$actions = $this->getActions($module, $uninstallable, 'not_install');
					} else {
						$actions = $this->getActions($module, $uninstallable, 'install');
					}
				} else {
					if($remote_version > $local_version) {
						$status = '<span class="ui-state-installed">installed: '.$local_version.'</span><br/>';
						$status .= '<span class="ui-state-update">new version available!</span><br/>';

						$actions = $this->getActions($module, $uninstallable, 'update');

					} else {
						$status = '<span class="ui-state-installed">installed: '.$local_version.'</span>';
						$actions = $this->getActions($module, $uninstallable, 'edit');
					}
				}
			} else {
				$theme = isset($categories['admin-theme']) ? '&theme=1' : '' ;
				$actions = $this->getActions($module, $uninstallable, 'download', $theme);
			}

			$this->module_table->row(array(
				'<b class="mm_mname">' . $module->class_name . '</b>' . '<br/>'
					.  $remote_version . " " . $module->release_state->title,
				'<b>' . $module->title . '</b><br/>' . $module->summary . '<a href="'.$module->url.'" target="_blank" class="icon"> '
					. $this->_("more") . '</a>' . $dependencies,
				implode(', ', $categories),
				implode(', ', $authors),
				date('Y/m/d', $module->created),
				date('Y/m/d', $module->modified),
				'+' . $module->likes,
				$status,
				$actions
			));

		}



		$categories_form = $this->createCategoryForm()->render();
		$form = $this->createForm()->render();

		$pretext = '<p>Modules found on modules.processwire.com ('.$count.') </p>';
		//$pretext .= 'ProcessWire Version ' . $this->config->version;
		$info = $this->getModuleInfo();
		return $pretext . $categories_form . $form .  '<p>Modules Manager v'.$info['version'].'</p>';
	}


	public function executeDownload() {

		$this->modules->resetCache();

		$url = $this->input->get->url;
		$class_name = $this->input->get->class;

		$tmp_dir = $this->config->paths->assets;
		$tmp_zip = $tmp_dir . $this->downloadFileName;

		if(!is_writable($this->config->paths->assets)) $this->error($this->_('Make sure assets directory is writeable for PHP.'));
		if(!is_writable($this->config->paths->siteModules)) $this->error($this->_('Make sure your site modules directory is writeable for PHP.'));

		// download the zip file and save it in assets directory
		$success = false;
		if($file = $this->downloadFile($url, $tmp_zip)) {
			$this->message('Downloaded zip file successfully from '.$url);
			// if successfully downloaded extract it
			$zip = new ZipArchive;
			if($zip->open($file) === true) {
				for($i = 0; $i < $zip->numFiles; $i++) {
					$zip->extractTo($tmp_dir, array($zip->getNameIndex($i)));
				}
				$extracted_directory_name = trim($zip->getNameIndex(0),'/');
				$zip->close();
			} else {
				throw new WireException('Could not open zip file');
			}
			// now create module directory and copy files over
			// if it's an admin theme we place it in site folder or remove current
			// if any found
			if($this->input->get('theme')){
				// look for a templates-admin folder
				if(glob($tmp_dir . $extracted_directory_name . '/templates-admin', GLOB_ONLYDIR)){
					$from = $tmp_dir . $extracted_directory_name . '/templates-admin/';
				} else {
					$from = $tmp_dir . $extracted_directory_name . '/';
				}
				$destination_directory = $this->config->paths->root . 'site/templates-admin';

				// remove the templates-admin folder if present
				if(file_exists($destination_directory)){
					if(strlen($destination_directory) > 0){
						if(!$this->removeDir($destination_directory)) throw new WireException('Could not remove templates-admin folder in site folder');
					}
				}
			} else {
				$from = $tmp_dir . $extracted_directory_name . '/';
				$destination_directory = $this->config->paths->siteModules . $class_name;
			}
			if($this->createDirectory($destination_directory)) {
				if($this->recursiveCopy( $from, $destination_directory)) {
					$this->message('Successfully copied files  to the directory: '.$destination_directory);
					$success = true;
				}
			} else {
				$this->error('Could not create directory: '.$destination_directory);
			}

			// remove downloaded zip and extracted folder
			if(!unlink($tmp_zip)) throw new WireException('Could not delete downloaded zip file '.$tmp_zip);
			if(strlen($extracted_directory_name) > 0){
				if(!$this->removeDir($tmp_dir . $extracted_directory_name)) throw new WireException('Could not delete downloaded temporary files '.$tmp_dir.$extracted_directory_name);
			}

		}

		// downloading and extracting is successful
		// lets show some install information
		if(!$success) {
			return '<p>' . $this->_('There seems to be a problem with downloading or writing the module.') . '</p>';
		}

		// reset modules cache, so we can install the module and PW knows about it
		$this->modules->resetCache();

		if($this->input->get('theme')){
			$str = sprintf($this->_('Admin theme `%s` downloaded and extracted successfully. If it worked you should see the new theme already. If not you may clear your cache or refresh the page.'),$class_name);
			$text = '<p>' . $str  . '</p>';
			return $text;
		}

		// check if modules isn't already installed and this isn't an update
		if(!$this->modules->isInstalled($class_name)) {
			$this->session->redirect("../install/?class=$class_name");
		} else {
			$this->fuel->set('processHeadline', 'You just updated '.$class_name);
			$str = sprintf($this->_('Module `%s` was updated successfully. Ready to check if everything still work! Or if there are possibly new options.'),$class_name);
			$text = '<p>' . $str . ' Module: <a href="'.$this->pages->get(21)->url.'edit?name='.$class_name.'">'.$class_name.'</a></p>';
		}
		return $text;
	}

	public function executeInstall() {

		$this->initModules(); // fix problems with modules extending modules not yet installed

		$class_name = $this->input->get->class;
		if(!$class_name) return $this->_("No class name found in GET parameter");

		$this->fuel->set('processHeadline', $this->_("Module Download Page"));

		$ptitle = sprintf($this->_("Downloaded: '%s'"), $class_name);
		$text = "<h2>$ptitle</h2>";

		$str = $this->_('Module downloaded and extracted successfully. If the modules allows it you can install it directly from here or any time later on the Modules admin page.');
		$text .= '<p>' . $str . '</p>';

		$info = $this->modules->getModuleInfo($class_name);

		if(count($info['requires'])) {
			$requires = $this->modules->getRequiresForInstall("ProcessLanguageTranslatorPlus");
			if(count($requires)) {
				$text .= "<p><b>" . $this->_("Sorry, you can't install this module now. It requires other module to be installed first") . ":</b><br/>";
				$text .= "<span class='notes'>$this->labelRequires - " . implode(', ', $requires) . "</span></p>";
			}
		} else $requires = array();

		$form = $this->modules->get('InputfieldForm');
		$form->attr('action', $this->pages->get(21)->url );
		$form->attr('method', 'post');
		$form->attr('id', 'modules_form');

		$field = '<input type="hidden" name="install" value="'.$class_name.'"/>';
		$form->value .= $field;

		if(!count($requires)) {
			$submit = $this->modules->get('InputfieldSubmit');
			$submit->attr('name', 'submit');
			$submit->attr('value', $this->_('install module'));
			$submit->columnWidth = 50;
			$form->add($submit);
		}

		$button = $this->modules->get('InputfieldButton');
		$button->attr('href', '../');
		$button->attr('value', $this->_('back to Modules Manager'));
		$button->attr('id', 'backtomanagerbutton');
		$button->columnWidth = 100;
		$form->add($button);

		$text .= $form->render();

		return $text;
	}

	public function createForm(){
		// build form
		$form = $this->modules->get('InputfieldForm');
		$form->attr('action', $this->pages->get(21)->url);
		$form->attr('method', 'post');
		$form->attr('id', 'modules_form');

		// refresh button
		$submit = $this->modules->get('InputfieldButton');
		$submit->attr('href', './?reset=1');
		$submit->attr('name', 'reset');
		$submit->attr('value', $this->_('refresh'));
		$submit->attr('class', $submit->attr('class') . ' head_button_clone');
		$form->add($submit);

		$table = $this->module_table->render();
		// add table and button to form field wrapper
		$form->attr('value', $table);

		return $form;

	}

	public function createCategoryForm(){

		// category select filter
		$categories_form = $this->modules->get('InputfieldForm');
		$categories_form->attr('action', './');
		$categories_form->attr('method', 'get');
		$categories_form->attr('id', 'modules_filter_form');

		// category select
		$cats = $this->modules->get('InputfieldSelect');
		$cats->attr('id+name', 'cat');
		$cats->label = $this->_('Filter categories');
		$categories = array_merge($this->all_categories, array('' => ''));

		//$all_categories = array_diff($all_categories, $this->exclude_categories);
		ksort($categories);

		$cats->addOptions($categories);
		$cats->value = wire('input')->get->cat; // selected the current requested GET
		$cats->attr('onchange', 'submit()');
		$cats->columnWidth = 70;
		$categories_form->append($cats);


		// category select
		$search = $this->modules->get('InputfieldText');
		$search->attr('id+name', 'mm_filter');
		$search->label = $this->_('Live Search');
		$search->attr("type","search");
		$search->columnWidth = 30;
		$categories_form->append($search);

		return $categories_form;
	}

	private function getActions($module, $uninstallable, $action='', $theme='') {

		if($uninstallable) {
			return '(uninstallable)<br/><a href="'.$module->url.'" target="_blank" title="Uninstallable with Modules Manager">more</a>';
		}

		$confirm = '';

		if($theme) {
			$install_text = $this->_('This will install the theme and delete the previous! If you have altered the /site/templates-admin/ theme or have your own, you might consider backing it up first.');
			$confirm = " onclick='return confirm(\"$install_text\");'";
		} else {
			$install_text = $this->_('Ensure that you trust the source of the ZIP file before continuing!');
			$confirm = " onclick='return confirm(\"$install_text\");'";
		}

		if($module->download_url) {
			if(substr($module->download_url,0,8) == 'https://' && !extension_loaded('openssl')) {
				$actions = 'no openssl installed!';
			} else {
				$button = $this->modules->get('InputfieldMarkup');
				if($action == 'edit') {
					$url = "{$this->pages->get(21)->url}edit?name={$module->class_name}";
					$button->value = "<a href='$url' id='{$module->class_name}'>" . $this->_("edit") . "</a>";
				}
				else if($action == 'update') {
					$url = "{$this->page->url}download/?url={$module->download_url}&class={$module->class_name}{$theme}";
					$button->value = "<a href='$url'$confirm id='{$module->class_name}'>" . $this->_("update") . "</a>";
				}
				else if($action == 'download') {
					$url = "{$this->page->url}download/?url={$module->download_url}&class={$module->class_name}{$theme}";
					$button->value = "<a href='$url'$confirm id='{$module->class_name}'>" . $this->_("download") . "</a>";

				}
				else if($action == 'install') {
					$button->value = "<button name='install' value='{$module->class_name}'>" . $this->_("install") . "</button>";
				}
				else if($action == 'not_install') {
					$button->value = "<button name='not_install' disabled='disabled' value='{$module->class_name}'><s>" . $this->_("install") . "</s></button>";
				}

				$actions = $button->render();
			}
		} else {
			// in case a module has no dl url but is already downloaded and can be installed
			if($this->modules->isInstallable($module->class_name)) {
				$actions = "<button name='install' value='{$module->class_name}'>install</button>";
			} else {
				$actions = '<a href="'.$module->url.'" target="_blank" title="No download URL found">more</a>';
			}
		}
		return $actions;
	}


	private function downloadFile($url, $fileName) {

		if((substr($url,0,8) == 'https://') && ! extension_loaded('openssl')) {
			$this->error('OpenSSL extension required but not available. File could not be downloaded from '.$url);
			return false;
		}

		// Define the options
		$options = array('max_redirects' => $this->getConfig('max_redirects') );
		$context = stream_context_create(array('http' => $options));

		// download the zip
		if(!$content = file_get_contents($url, $fileName, $context)) {
			$this->error('File could not be downloaded '.$url);
			return false;
		}

		if(($fp = fopen($fileName, 'wb')) === false) {
			$this->error('fopen error for filename '.$fileName);
			return false;
		}

		fwrite($fp, $content);
		fclose($fp);
		return $fileName;
	}

	private function recursiveCopy($source_directory, $destination_directory){
		// recursive function to copy
		// all subdirectories and contents:
		if(is_dir($source_directory)) $directory_handle = opendir($source_directory);
		$directory_name = substr($source_directory,strrpos($source_directory,'/')+1);

		wireMkdir($destination_directory . '/' . $directory_name);
		if($directory_handle != false){
			while($file = readdir($directory_handle)) {
				if($file != '.' && $file != '..') {
					if(!is_dir($source_directory . '/' . $file)) {
						copy ($source_directory . '/' . $file, $destination_directory . $directory_name . '/' .$file);
					} else {
						$this->recursiveCopy($source_directory . '/' . $file, $destination_directory . $directory_name . '/');
					}
				}
			}
			closedir($directory_handle);
		}
		return true;
	}

	private function createDirectory($directory){
		if(!file_exists($directory)) {
			if(!wireMkdir($directory)) {
				$this->error('error creating module directory at: '.$directory);
				return false;
			}
		}
		return true;
	}

	private function removeDir($dir){
		foreach(scandir($dir) as $file) {
			if($file === '.' || $file === '..') continue;
			if(is_dir($dir .'/'. $file)) {
				$this->removeDir($dir .'/'. $file);
			} else{
				if(!unlink($dir .'/'. $file)) throw new WireException('Could not remove file '.$file);
			}
		}
		if(!rmdir($dir)) throw new WireException('Could not remove directory '.$dir);
		return true;
	}

	private function createCacheFile($cache_file) {
		$contents = file_get_contents($this->getConfig('remoteurl') . '?apikey=' . $this->getConfig('apikey') . '&limit=' . $this->getConfig('limit'));
		if(!$handle = fopen($cache_file, 'w')) throw new WireException('cannot create cache file '.$cache_file);
		if(!fwrite($handle, $contents)) throw new WireException('cannot write cache file '.$cache_file);
		fclose($handle);
		return json_decode($contents);
	}

	private function readCacheFile($cache_file) {
		if(!$handle = fopen($cache_file, 'r')) throw new WireException('cannot open cache file '.$cache_file);
		if(!$contents = fread($handle, filesize($cache_file))) throw new WireException('cannot read cache file '.$cache_file);
		fclose($handle);
		return json_decode($contents);
	}

	public function install() {
		// page already found for some reason
		$ap = $this->pages->find('name='.__CLASS__)->first();
		if($ap->id) {
            if(!$ap->process) {
                    $ap->process = $this;
                    $ap->save();
            }
            return;
        }
		$p = new Page();
		$p->template = $this->templates->get('admin');
		$p->title = __CLASS__;
		$p->name = __CLASS__;
		$p->parent = $this->pages->get(22);
		$p->process = $this;
		$p->save();
	}

	public function uninstall() {
		$found = $this->pages->find('name='.__CLASS__)->first();
		if($found->id) $found->delete();
		$cache_file = $this->config->paths->cache . $this->cacheFile;
		if(file_exists($cache_file)) {
			if(!unlink($cache_file)) throw new WireException('Could not delete cache file '.$cache_file);
			else $this->message('Cache file deleted successfully '.$cache_file);
		}

	}

	static public function getModuleConfigInputfields(array $data) {
		$data = array_merge(self::$defaults, $data);

		$fields = new InputfieldWrapper();
		$modules = wire('modules');

		$field = $modules->get('InputfieldText');
		$field->attr('name', 'apikey');
		$field->attr('size', 10);
		$field->attr('value', $data['apikey']);
		// $field->set('collapsed',Inputfield::collapsedHidden);
		$field->label = 'modules.processwire.com APIkey';
		$fields->append($field);

		$field = $modules->get('InputfieldText');
		$field->attr('name', 'remoteurl');
		$field->attr('size', 0);
		$field->attr('value', $data['remoteurl']);
		$field->label = 'URL to webservice';
		$fields->append($field);

		$field = $modules->get('InputfieldInteger');
		$field->attr('name', 'limit');
		$field->attr('value', $data['limit']);
		$field->label = 'Limit';
		$fields->append($field);

		$field = $modules->get('InputfieldInteger');
		$field->attr('name', 'max_redirects');
		$field->attr('value', $data['max_redirects']);
		$field->label = 'Max Redirects for file_get_contents stream context (in case)';
		$fields->append($field);

		return $fields;
	}
}
